### ISSUE TITLE
Error when using RNetlogo to start Netlogo

### ISSUE THREAD

**Issue by catseesun** [NetLogo/NetLogo#1534]
I have encountered error when starting Netlogo using RNetLogo in R. I have tried all the potential solutions I can find online, but still haven't figured out the issue. Would appreciate it if someone can help. 

Code: 
library(RNetLogo)
nl.path = "C:/Program Files/NetLogo 5.3/app"
NLStart(nl.path, gui=FALSE, nl.jarname = 'NetLogo.jar')

Error message:
java.lang.NoClassDefFoundError: org/nlogo/api/Exceptions$Handler
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
Caused by: java.lang.ClassNotFoundException
	at RJavaClassLoader.findClass(RJavaClassLoader.java:383)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 2 more

Version:
- system: Windows 10
- R: 3.3.3
- Netlogo: 5.3/5.3.1/6.0/6.0.2 (tried all of them, same error message)
- Java: 1.8.0_151-b12 (this is the one called in R, checked by .jcall)
- RNetlogo and rJava are most up-to-date as of 1/9/2018

**Comment by mrerrormessage** [comment]
It looks like you're specifying an old-style `nl.jarname`. [This comment](https://github.com/NetLogo/NetLogo/issues/1282#issuecomment-302152506) offers more information on how you can change the `NLStart` call. Closing this issue because this is an RNetLogo problem, but if you have follow-up questions, feel free to post them as comments and I'll try to respond.

**Comment by catseesun** [comment]
@mrerrormessage Thanks for your response Robert! I updated nl.jarname according different Netlogo versions. Starting from Netlogo 6.0, the nl.jarname changes to be something like "Netlogo-6.0.0.jar", and I have tried that but with no luck. 

All the combinations I have tried: 
- Netlogo 5.3
nl.path = "C:/Program Files/NetLogo 5.3/app"
NLStart(nl.path, gui=FALSE, nl.jarname = 'NetLogo.jar')

-Netlogo 5.3.1
nl.path = "C:/Program Files/NetLogo 5.3.1/app"
NLStart(nl.path, gui=FALSE, nl.jarname = 'NetLogo.jar')

-Netlogo 6.0
nl.path = "C:/Program Files/NetLogo 6.0/app"
NLStart(nl.path, gui=FALSE, nl.jarname = 'netlogo-6.0.0.jar')

-Netlogo 6.0
nl.path = "C:/Program Files/NetLogo 6.0/app"
NLStart(nl.path, gui=FALSE, nl.jarname = 'netlogo-6.0.0.jar')

-Netlogo 6.0.2
nl.path = "C:/Program Files/NetLogo 6.0.2/app"
NLStart(nl.path, gui=FALSE, nl.jarname = 'netlogo-6.0.2.jar')

**Comment by mrerrormessage** [comment]
Sometimes NetLogo ends up in `C:\Program Files (x86)\NetLogo <version>`. Can you check whether it's there for your NetLogo installation(s)? If so, you'll need to change `nl.path`.

**Comment by catseesun** [comment]
I did check the installation path. The app is in `C:\Program Files\NetLogo <version>`.

**Comment by mrerrormessage** [comment]
What does `Sys.getenv("R_ARCH")` return for you? Have you tried the above in R i386 as well as R x86-64?

**Comment by catseesun** [comment]
Solved the problem! Two things combined make it work: 1) change to R i386 as you suggested; 2) download the previous RNetLogo version (1.0-2) from https://cran.r-project.org/src/contrib/Archive/RNetLogo/

So essentially it seems to be a version mismatch problem. Thanks a lot for your suggestions!

**Comment by vonjd** [comment]
Unfortunately, I get the same error. I use RNetLogo 1.0.4, rJava 0.9.11 and JAVA Version 8 Update 221
Release date July 16, 2019 with R 3.6.1 and NetLogo 6.1.0. `Sys.getenv("R_ARCH")` gives `"/x64"`

It works with NetLogo 6.0.4, so they obviously changed something yet again.

I guess there is no other chance than to stay with NetLogo 6.0.4 right?!? It is really unfortunate that RNetLogo is not maintained any more...

**Comment by vonjd** [comment]
This might perhaps help: When I start NetLogo with `NLStart ` and `gui = FALSE` and load the model I get:
`"Java-Object{java.lang.NoSuchMethodError: org.nlogo.workspace.Controllable.open(Ljava/lang/String;)V}"`

**Comment by LaCuneta** [comment]
@vonjd Another option to try is [nlrx](https://ropensci.github.io/nlrx/), which seems to do a lot of the same things as RNetLogo.  I haven't tried it yet, but it appears to be more actively maintained.

**Comment by tonysdatamodels** [comment]
> Solved the problem! Two things combined make it work: 1) change to R i386 as you suggested; 2) download the previous RNetLogo version (1.0-2) from https://cran.r-project.org/src/contrib/Archive/RNetLogo/
> 
> So essentially it seems to be a version mismatch problem. Thanks a lot for your suggestions!

**Comment by tonysdatamodels** [comment]
> Solved the problem! Two things combined make it work: 1) change to R i386 as you suggested; 2) download the previous RNetLogo version (1.0-2) from https://cran.r-project.org/src/contrib/Archive/RNetLogo/
> 
> So essentially it seems to be a version mismatch problem. Thanks a lot for your suggestions!

Very good that you solved the problem. Mines actually works in R x 64. I think they key is to make sure R, Netlogo and Java are all either 64 bit or 32 bit. I have a video on youtube (https://www.youtube.com/watch?v=zWMdaTEPTOc) about the opening procedure for NetLogo in Rand the code I used is below https://raw.githubusercontent.com/tonysdatamodels/netlogo.in.r/main/open%20netlogo%20in%20r
