### PR TITLE
upgrade ScalaTest and ScalaCheck

### LINKED ISSUE #1974: ScalaTest 3.0.6+ deprecation errors
I looked deeper in the issues updating scalatest. Scalatest [3.0.6](https://www.scalatest.org/release_notes/3.0.6) and [3.0.8](https://www.scalatest.org/release_notes/3.0.8) introduce new depreciations blocking the update, the first one I encountered being:

- Deprecated ScalaCheck related classes in `org.scalatest.prop`, moved the classes into `org.scalatestplus.scalacheck`.

So I tried updating to Scalatest 3.0.9 (the latest 3.0.x version) on [this branch](https://github.com/EwoutH/NetLogo/tree/update/scalatest-3.0.9), in which the CI then [got stuck](https://github.com/EwoutH/NetLogo/runs/4092802696?check_suite_focus=true#step:7:312) on an unused import error (`org.scalatest.prop`). When I removed that import on [this branch](https://github.com/EwoutH/NetLogo/tree/update/scalatest-3.0.9-fix), a load of [deprecation warnings](https://github.com/EwoutH/NetLogo/runs/4092802696?check_suite_focus=true#step:7:312) appeared.

<details><summary>ScalaTest depreciation errors</summary>

```
Error:  /home/runner/work/NetLogo/NetLogo/netlogo-core/src/test/api/ProgramGenerator.scala:11:32: trait GeneratorDrivenPropertyChecks in package prop is deprecated: GeneratorDrivenPropertyChecks has been moved from org.scalatest.prop to org.scalatestplus.scalacheck and renamed as ScalaCheckDrivenPropertyChecks. Please update your imports, as this deprecated type alias will be removed in a future version of ScalaTest.
Error:  trait ProgramGenerator extends GeneratorDrivenPropertyChecks {
Error:                                 ^
Error:  /home/runner/work/NetLogo/NetLogo/netlogo-core/src/test/fileformat/HubNetWidgetReadersTests.scala:144:53: trait GeneratorDrivenPropertyChecks in package prop is deprecated: GeneratorDrivenPropertyChecks has been moved from org.scalatest.prop to org.scalatestplus.scalacheck and renamed as ScalaCheckDrivenPropertyChecks. Please update your imports, as this deprecated type alias will be removed in a future version of ScalaTest.
Error:  class HubNetWidgetReadersTest extends FunSuite with GeneratorDrivenPropertyChecks {
Error:                                                      ^
Error:  /home/runner/work/NetLogo/NetLogo/netlogo-core/src/test/fileformat/HubNetWidgetReadersTests.scala:149:27: object CheckerAsserting in package enablers is deprecated: CheckerCheckerAssertings has been moved from org.scalatest.enablers to org.scalatestplus.scalacheck. Please update your imports, as this deprecated type will be removed in a future version of ScalaTest.
Error:      forAll(hubNetWidgets) { (widget: Widget) =>
Error:                            ^
Error:  /home/runner/work/NetLogo/NetLogo/netlogo-core/src/test/fileformat/ThreeDViewReaderTests.scala:14:50: trait GeneratorDrivenPropertyChecks in package prop is deprecated: GeneratorDrivenPropertyChecks has been moved from org.scalatest.prop to org.scalatestplus.scalacheck and renamed as ScalaCheckDrivenPropertyChecks. Please update your imports, as this deprecated type alias will be removed in a future version of ScalaTest.
Error:  class ThreeDViewReaderTest extends FunSuite with GeneratorDrivenPropertyChecks {
Error:                                                   ^
Error:  /home/runner/work/NetLogo/NetLogo/netlogo-core/src/test/fileformat/ThreeDViewReaderTests.scala:44:31: object CheckerAsserting in package enablers is deprecated: CheckerCheckerAssertings has been moved from org.scalatest.enablers to org.scalatestplus.scalacheck. Please update your imports, as this deprecated type will be removed in a future version of ScalaTest.
Error:      forAll(threeDViewWidgets) { (view: View) =>
Error:                                ^
Error:  /home/runner/work/NetLogo/NetLogo/netlogo-core/src/test/nvm/BindingTests.scala:12:42: trait GeneratorDrivenPropertyChecks in package prop is deprecated: GeneratorDrivenPropertyChecks has been moved from org.scalatest.prop to org.scalatestplus.scalacheck and renamed as ScalaCheckDrivenPropertyChecks. Please update your imports, as this deprecated type alias will be removed in a future version of ScalaTest.
Error:  class BindingTests extends FunSuite with GeneratorDrivenPropertyChecks {
Error:                                           ^
Error:  /home/runner/work/NetLogo/NetLogo/netlogo-gui/src/test/api/FileIOTests.scala:44:42: trait PropertyChecks in package prop is deprecated: PropertyChecks has been moved from org.scalatest.prop to org.scalatestplus.scalacheck and renamed as ScalaCheckPropertyChecks. Please update your imports, as this deprecated type alias will be removed in a future version of ScalaTest.
Error:  class FileIOTests2 extends PropSpec with PropertyChecks {
Error:                                           ^
Error:  /home/runner/work/NetLogo/NetLogo/netlogo-gui/src/test/api/FileIOTests.scala:50:54: object CheckerAsserting in package enablers is deprecated: CheckerCheckerAssertings has been moved from org.scalatest.enablers to org.scalatestplus.scalacheck. Please update your imports, as this deprecated type will be removed in a future version of ScalaTest.
Error:      forAll(arbitrary[String], Gen.chooseNum(1, 4096))(
Error:                                                       ^
Error:  /home/runner/work/NetLogo/NetLogo/netlogo-gui/src/test/ide/NetLogoFoldParserTest.scala:41:32: object CheckerAsserting in package enablers is deprecated: CheckerCheckerAssertings has been moved from org.scalatest.enablers to org.scalatestplus.scalacheck. Please update your imports, as this deprecated type will be removed in a future version of ScalaTest.
Error:      forAll(wellFormedPrograms) { p =>
Error:                                 ^
Error:  /home/runner/work/NetLogo/NetLogo/netlogo-gui/src/test/ide/NetLogoFoldParserTest.scala:47:32: object CheckerAsserting in package enablers is deprecated: CheckerCheckerAssertings has been moved from org.scalatest.enablers to org.scalatestplus.scalacheck. Please update your imports, as this deprecated type will be removed in a future version of ScalaTest.
Error:      forAll(onceMangledProgram) { p =>
Error:                                 ^
Error:  /home/runner/work/NetLogo/NetLogo/netlogo-gui/src/test/util/HexStringTests.scala:24:45: trait PropertyChecks in package prop is deprecated: PropertyChecks has been moved from org.scalatest.prop to org.scalatestplus.scalacheck and renamed as ScalaCheckPropertyChecks. Please update your imports, as this deprecated type alias will be removed in a future version of ScalaTest.
Error:  class HexStringTests2 extends PropSpec with PropertyChecks {
Error:                                              ^
Error:  /home/runner/work/NetLogo/NetLogo/netlogo-gui/src/test/util/HexStringTests.scala:28:11: object CheckerAsserting in package enablers is deprecated: CheckerCheckerAssertings has been moved from org.scalatest.enablers to org.scalatestplus.scalacheck. Please update your imports, as this deprecated type will be removed in a future version of ScalaTest.
Error:      forAll((ns: Array[Int]) =>
Error:            ^
Error:  /home/runner/work/NetLogo/NetLogo/netlogo-gui/src/test/util/HexStringTests.scala:32:11: object CheckerAsserting in package enablers is deprecated: CheckerCheckerAssertings has been moved from org.scalatest.enablers to org.scalatestplus.scalacheck. Please update your imports, as this deprecated type will be removed in a future version of ScalaTest.
Error:      forAll((ns: Array[Byte]) =>
Error:            ^
Error:  /home/runner/work/NetLogo/NetLogo/netlogo-gui/src/test/util/HexStringTests.scala:37:11: object CheckerAsserting in package enablers is deprecated: CheckerCheckerAssertings has been moved from org.scalatest.enablers to org.scalatestplus.scalacheck. Please update your imports, as this deprecated type will be removed in a future version of ScalaTest.
Error:      forAll((ns: Array[Int]) =>
Error:            ^
Error:  /home/runner/work/NetLogo/NetLogo/netlogo-gui/src/test/util/HexStringTests.scala:41:11: object CheckerAsserting in package enablers is deprecated: CheckerCheckerAssertings has been moved from org.scalatest.enablers to org.scalatestplus.scalacheck. Please update your imports, as this deprecated type will be removed in a future version of ScalaTest.
Error:      forAll((ns: Array[Byte]) =>
Error:            ^
Error:  /home/runner/work/NetLogo/NetLogo/netlogo-gui/src/test/util/HexStringTests.scala:54:11: object CheckerAsserting in package enablers is deprecated: CheckerCheckerAssertings has been moved from org.scalatest.enablers to org.scalatestplus.scalacheck. Please update your imports, as this deprecated type will be removed in a future version of ScalaTest.
Error:      forAll((ns: Array[Byte]) =>
Error:            ^
Error:  /home/runner/work/NetLogo/NetLogo/netlogo-gui/src/test/util/HexStringTests.scala:57:11: object CheckerAsserting in package enablers is deprecated: CheckerCheckerAssertings has been moved from org.scalatest.enablers to org.scalatestplus.scalacheck. Please update your imports, as this deprecated type will be removed in a future version of ScalaTest.
Error:      forAll((ns: Array[Int]) =>
Error:            ^
Error:  /home/runner/work/NetLogo/NetLogo/netlogo-gui/src/test/util/UtilsTests.scala:18:41: trait PropertyChecks in package prop is deprecated: PropertyChecks has been moved from org.scalatest.prop to org.scalatestplus.scalacheck and renamed as ScalaCheckPropertyChecks. Please update your imports, as this deprecated type alias will be removed in a future version of ScalaTest.
Error:  class UtilsTests2 extends PropSpec with PropertyChecks {
Error:                                          ^
Error:  /home/runner/work/NetLogo/NetLogo/netlogo-gui/src/test/util/UtilsTests.scala:20:11: object CheckerAsserting in package enablers is deprecated: CheckerCheckerAssertings has been moved from org.scalatest.enablers to org.scalatestplus.scalacheck. Please update your imports, as this deprecated type will be removed in a future version of ScalaTest.
Error:      forAll((ns: String) =>
Error:            ^
Error:  /home/runner/work/NetLogo/NetLogo/netlogo-gui/src/test/util/UtilsTests.scala:25:11: object CheckerAsserting in package enablers is deprecated: CheckerCheckerAssertings has been moved from org.scalatest.enablers to org.scalatestplus.scalacheck. Please update your imports, as this deprecated type will be removed in a future version of ScalaTest.
Error:      forAll((ns: String) =>
Error:            ^
Error:  /home/runner/work/NetLogo/NetLogo/netlogo-gui/src/test/window/SliderDataTests.scala:14:45: trait PropertyChecks in package prop is deprecated: PropertyChecks has been moved from org.scalatest.prop to org.scalatestplus.scalacheck and renamed as ScalaCheckPropertyChecks. Please update your imports, as this deprecated type alias will be removed in a future version of ScalaTest.
Error:  class SliderDataTests extends PropSpec with PropertyChecks {
Error:                                              ^
Error:  /home/runner/work/NetLogo/NetLogo/netlogo-gui/src/test/window/SliderDataTests.scala:41:37: object CheckerAsserting in package enablers is deprecated: CheckerCheckerAssertings has been moved from org.scalatest.enablers to org.scalatestplus.scalacheck. Please update your imports, as this deprecated type will be removed in a future version of ScalaTest.
Error:      forAll(genSlider, genBigDouble) { (s, d) =>
Error:                                      ^
Error:  /home/runner/work/NetLogo/NetLogo/netlogo-gui/src/test/window/SliderDataTests.scala:56:26: object CheckerAsserting in package enablers is deprecated: CheckerCheckerAssertings has been moved from org.scalatest.enablers to org.scalatestplus.scalacheck. Please update your imports, as this deprecated type will be removed in a future version of ScalaTest.
Error:      forAll(genPosOddInt) { (r) =>
Error:                           ^
Error:  /home/runner/work/NetLogo/NetLogo/netlogo-gui/src/test/window/SliderDataTests.scala:68:25: object CheckerAsserting in package enablers is deprecated: CheckerCheckerAssertings has been moved from org.scalatest.enablers to org.scalatestplus.scalacheck. Please update your imports, as this deprecated type will be removed in a future version of ScalaTest.
Error:      forAll(genSmallInt) { (i) =>
Error:                          ^
Error:  /home/runner/work/NetLogo/NetLogo/netlogo-gui/src/test/window/SliderDataTests.scala:127:36: object CheckerAsserting in package enablers is deprecated: CheckerCheckerAssertings has been moved from org.scalatest.enablers to org.scalatestplus.scalacheck. Please update your imports, as this deprecated type will be removed in a future version of ScalaTest.
Error:      forAll(genBigInt, genSmallInt) { (min, max) =>
Error:                                     ^
Error:  /home/runner/work/NetLogo/NetLogo/netlogo-gui/src/test/window/SliderDataTests.scala:136:11: object CheckerAsserting in package enablers is deprecated: CheckerCheckerAssertings has been moved from org.scalatest.enablers to org.scalatestplus.scalacheck. Please update your imports, as this deprecated type will be removed in a future version of ScalaTest.
Error:      forAll((min: Double) =>
Error:            ^
Error:  /home/runner/work/NetLogo/NetLogo/netlogo-gui/src/test/window/SliderDataTests.scala:141:11: object CheckerAsserting in package enablers is deprecated: CheckerCheckerAssertings has been moved from org.scalatest.enablers to org.scalatestplus.scalacheck. Please update your imports, as this deprecated type will be removed in a future version of ScalaTest.
Error:      forAll((s: SliderData) =>
Error:            ^
Error:  /home/runner/work/NetLogo/NetLogo/netlogo-gui/src/test/window/SliderDataTests.scala:164:12: object CheckerAsserting in package enablers is deprecated: CheckerCheckerAssertings has been moved from org.scalatest.enablers to org.scalatestplus.scalacheck. Please update your imports, as this deprecated type will be removed in a future version of ScalaTest.
Error:      forAll { (s: SliderData, constraint: DynamicSliderConstraint) =>
Error:             ^
Error:  28 errors found
Error:  (netlogo / Test / compileIncremental) Compilation failed
Error:  Total time: 112 s (01:52), completed Nov 3, 2021 1:33:19 PM
Error: Process completed with exit code 1.
```
</details>

I tried using [ScalaTest Autofix](https://github.com/scalatest/autofix) and [Scalafix](https://github.com/scalacenter/scalafix), but wasn't successful so far.

Part of #1968.

### PR DESCRIPTION
**Pull request by SethTisue**
fixes #1974

### CODE REVIEW

**Comment by SethTisue** [comment]
yay, CI likes it!

**Comment by EwoutH** [comment]
Awesome, thanks for the effort!

@LaCuneta Could you review/merge it?

**Review by LaCuneta — APPROVED** [review]
Looks good to me!  Thanks for the updates.  We're in code freeze at the moment, so this will be merged after the next NetLogo release is out (hopefully soon).

**Comment by SethTisue** [comment]
@EwoutH feel free to incorporate the commit in this PR into your own PRs, so you won't be blocked waiting for the unfreeze

**Comment by SethTisue** [comment]
now goes all the way to 3.2.x / 1.15.x

**Comment by EwoutH** [comment]
I have a nice set of dependency updates ready build on this, including Scala 2.12.15 and Scala.ja 1.7.1. After the code freeze, lets merge this first and then I will open a PR with those dependencies.

**Review by LaCuneta — APPROVED** [review]
Thank you again for getting these all updated!

**Comment by EwoutH** [comment]
Awesome! Based on you work I prepared #1981, which includes updates to Scala 2.12.15 and Scala.js 1.7.1!
