### ISSUE TITLE
RNetLogo Error loading models

### ISSUE THREAD

**Issue by jessicagn** [NetLogo/NetLogo#1782]
Hi, I've been trying to get RNetlogo working in R, but have been unsuccessful thus far. I believe it is starting up correctly, as NLStart runs without producing an error message, but when I try to load a model, I get the following error. If anyone has any ideas on how to fix this it would be super helpful! Thanks! :-)

> library(RNetLogo)
> nl.path <- "C:/Program Files/NetLogo 6.1.0/app"
> NLStart(nl.path,gui=FALSE,nl.jarname="netlogo-6.1.0.jar")
> model.path <- "C:/Program Files/NetLogo 6.1.0/app/models/Sample Models/Earth Science/Fire.nlogo"
> NLLoadModel(model.path)
[1] "Java-Object{java.lang.NoSuchMethodError: org.nlogo.workspace.Controllable.open(Ljava/lang/String;)V}"
Error in NLLoadModel(model.path) :

It may also be worth noting that when I try to run NLStart with gui=TRUE, I don't get an error message, but I can't do anything from there. I get .jcall errors with anything I run. For example:

> NLStart(nl.path,gui=TRUE,nl.jarname="netlogo-6.1.0.jar")
> NLQuit()
Error in .jcall(nl.obj, "V", "KillWorkspace") : 
  RcallMethod: invalid object parameter

**Comment by LaCuneta** [comment]
Hey jessicagn, thank you for your interest in NetLogo, sorry you ran into this issue.

This looks like a break in compatibility with NetLogo 6.1 and RNetLogo.  If you download NetLogo 6.0.4 (the last 6.0 release) you should be able to use RNetLogo with it.  I don't know if the RNetLogo project has plans to update for 6.1.0 or not at this point, their website is [here](http://rnetlogo.r-forge.r-project.org/).

**Comment by LaCuneta** [comment]
Forgot to add the download link for NetLogo 6.0.4:  http://ccl.northwestern.edu/netlogo/6.0.4/

**Comment by jessicagn** [comment]
Thank you for the update! It works with NetLogo 6.0.4. Just a heads up that it will not work with NetLogo 5.3.1 either. A quick follow up question. Why will it only work in headless mode? When I try to run it with the GUI open, I get

> NLStart(nl.path,gui=TRUE,nl.jarname='netlogo-6.0.4.jar')
java.awt.HeadlessException
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at javax.swing.SwingUtilities$SharedOwnerFrame.<init>(SwingUtilities.java:1763)
	at javax.swing.SwingUtilities.getSharedOwnerFrame(SwingUtilities.java:1838)
	at javax.swing.JOptionPane.getRootFrame(JOptionPane.java:1696)
	at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:863)
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:666)
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:637)
	at nlcon.NLink.<init>(NLink.java:109)

**Comment by LaCuneta** [comment]
For 5.3.1, if you need it, you'll probably have to go back to [version 1.0-2 of the RNetLogo package](https://cran.r-project.org/src/contrib/Archive/RNetLogo/).  

I'm not certain on that headless error, but it's coming from the RNetLogo side of things.  I would play with the settings being passed in a bit and see if anything makes a difference.
